# Site settings
title: Hexecontahedron
author: Alberto Barradas
description: > #
  This site is my personal notebook, you can find scraps, notes, and recipies of the stuff I do and want to share.
url: "hexecontahedron.com"
twitter_username: abcsds
github_username:  abcsds

# Build settings
markdown: redcarpet
highlighter: Pygments
paginate: 5
sass:
  sass_dir: _sass
  style: :compressed

exclude:
- README.md
- CNAME
- Gemfile
- Guardfile
