# Site settings
title: Hexecontahedron
author: Alberto Barradas
description: > #
  Cognitive Science, Data Science, Open Data, Sociology, Psichology, Computer Neuroscience, Math, and Engineering: This is my personal notebook, you can find notes of the stuff I do and want to share.
url: "hexecontahedron.com"
twitter_username: abcsds
github_username:  abcsds
personal_website: "http://AlbertoBarradas.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- Archive
