# Site settings
title: Hexecontahedron
author: Alberto Barradas
description: > #
  This site is my personal notebook, you can find scraps, notes, and recipies of the stuff I do and want to share.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "hexecontahedron.com" # the base hostname & protocol for your site
twitter_username: abcsds
github_username:  abcsds

# Build settings
markdown: redcarpet
highlighter: pygments
paginate: 5
sass:
  sass_dir: _sass
  style: :compressed
